apiVersion: nokia.com/v1alpha1
kind: ClusterClaim
metadata:
  name: team-a
  labels:
    cluster-owner: laurent
spec:
  id: team-a
  # to be updated
  account: 123456789012
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
      access: intranet
  parameters:
    # Possible values small, medium, large
    nodeSize: small
    # version: "1.21"
    # minNodeCount: 1
